update to msal4.30 + pkce support
AzureAD/microsoft-identity-web pull request #1152
Opened 2021-04-20 21:28 UTC by jennyf19

@jmprieur have not tested yet, but thought you might be interested as well.

2021-04-20 21:29 UTC, jennyf19 commented on src/Microsoft.Identity.Web/TokenAcquisition.cs
> +                context.Properties.Items.TryGetValue(OAuthConstants.CodeVerifierKey, out string? codeVerifier);
might move this inline, but leaving as-is for testing.

2021-04-20 21:52 UTC, jennyf19 commented on src/Microsoft.Identity.Web/TokenAcquisition.cs
> +                context.TokenEndpointRequest.Parameters.TryGetValue(OAuthConstants.CodeVerifierKey, out string? codeVerifier);
can move this inline, but left for testing.

2021-04-21 13:04 UTC, jmprieur reviewed
LTGM @jennyf19 
I also tried by overriding `usePkce = false` in the OpenIdConnectOptions;

2021-04-21 13:07 UTC, jmprieur requested changes
We shouldn't remove line 434 of  src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs

otherwise 

.AddMicrosoftIdentityWebApp()

and then

```CSharp
services.ConfigureOptions<MicrosoftIdentityOptions>(options =>
{
 options.UsePkce = false;
});
```

would not do the right thing?

2021-04-21 13:49 UTC, bgavrilMS commented
How do you know that this works?

2021-04-21 14:43 UTC, jmprieur commented
@bgavrilMS : you run the WebAppCallsWebApi projects and use the todo-list button to call the web API.
When you sign-in, this is used (By default PKCE is enabled in ASP.NET Core 5.0); 

The other thing to test is that if you override OpenIdConnectOptions.UsePkce to false, this still works (and it does)

2021-04-21 15:25 UTC, jennyf19 commented
@bgavrilMS we discussed thursday, the testing would have to happen in MSAL.NET, which I think you added. I tested it manually, as we discussed, i put a break point and checked the code verifier was included and also checked when it's not. everything would break if it didn't work. I'm not testing cca.GetAuthorizationRequestUrl, as we don't use it.

2021-04-21 15:30 UTC, jennyf19 commented on src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs
>  #if DOTNET_50_AND_ABOVE
yes. i re-added it.

2021-04-21 15:33 UTC, jmprieur approved these changes
LGTM
Thanks @jennyf19

2021-04-22 16:30 UTC, merged

2021-04-26 08:59 UTC, bgavrilMS commented
@jennyf19 - you have an E2E / Selenium test I believe. Will it use PKCE now? 
I am asking if the team needs to manually validate this scenario on every release or if it is covered by existing automation.

2021-04-26 17:17 UTC, jennyf19 commented
@bgavrilMS I don't understand what the issue is...? We use PKCE now always, so it just works. Not sure what you are asking.

2021-04-30 19:31 UTC, tedvanderveen commented
@jennyf19 great work, can we pick it up in a nightly build package or should we wait for next Nuget release?

2021-04-30 23:52 UTC, jennyf19 commented
@tedvanderveen i've been focused on getting an enhancement out for handling multiple auth schemes....I will sync with @jmprieur and maybe we'll do a release with this and a few other completed items in [1.10 project board](https://github.com/AzureAD/microsoft-identity-web/projects/24) so we aren't holding things up for the larger enhancement work with auth schemes.

2021-05-01 04:33 UTC, jennyf19 commented
@tedvanderveen actually, follow [1.9.2](https://github.com/AzureAD/microsoft-identity-web/projects/25), which will have the PCKE included. We will try to have it out next week (1st week of May).

2021-05-03 07:16 UTC, tedvanderveen commented
@jennyf19 looks like 1.9.2 is ready to roll. Great work!

2021-05-04 17:28 UTC, jennyf19 commented
@tedvanderveen 1.9.2 is out. should be on nuget shortly: Included in [1.9.2 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.9.2)