OneBranch Migration
AzureAD/microsoft-identity-web pull request #2777
Opened 2024-04-19 07:11 UTC by trwalke

# OneBranch Migration

- [ ] You've read the [Contributor Guide](https://github.com/AzureAD/microsoft-identity-web/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/AzureAD/microsoft-identity-web/blob/master/CODE_OF_CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}

Fixes #{bug number} (in this specific format)

2024-04-19 12:37 UTC, bgavrilMS commented on build/template-onebranch-release-build.yaml
> +  MsIdentityWebSemVer: '1.0.0-devopsbuild'
I recommend something like `1.0.0-internal$(Build.BuildNumber)`

2024-04-19 12:37 UTC, bgavrilMS approved these changes

2024-04-19 21:18 UTC, jennyf19 commented
where do the packages go now? we check them manually to ensure things are signed correctly.

2024-04-19 21:19 UTC, jennyf19 commented
there is an npm error in ADO:
<img width="371" alt="image" src="https://github.com/AzureAD/microsoft-identity-web/assets/19942418/f637d2d2-9d20-477a-ac4a-1359935b851f">

and some warnings seem relevant to these changes and should be fixed.

2024-04-19 21:20 UTC, jennyf19 requested changes
left a few questions

2024-04-19 21:32 UTC, trwalke commented
Looking at warnings/error.

Packages can be found here @jennyf19 
![image](https://github.com/AzureAD/microsoft-identity-web/assets/30090357/f59bbf0a-a656-40e3-8511-18e7034936f5)

2024-04-23 06:13 UTC, trwalke commented
> there is an npm error in ADO: <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/19942418/324120058-f637d2d2-9d20-477a-ac4a-1359935b851f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTI5NzksIm5iZiI6MTcxMzg1MjY3OSwicGF0aCI6Ii8xOTk0MjQxOC8zMjQxMjAwNTgtZjYzN2QyZDItOWQyMC00NzdhLWFjNGEtMTM1OTkzNWI4NTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA2MTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYjk2MTI2ZmRmNjkyZDhlOTdhNDc0MmU5Y2M3ZTcwMDE3ZmIxN2QxNjhhNGJjNGRiNjY0OWQ2MjA0ZGRmZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tur4dCTPjfR7Vn9FWFRBMfzFTNDz_gGo-XqdNMRjphg">
> 
> and some warnings seem relevant to these changes and should be fixed.

@jennyf19 resolved the error that you were seeing in the latest build.
A lot of the additional warnings are a result of the Onebranch tasks and I dont really have any way to resolve them. 
Most of them can be ignored as they do not affect the operation of the build.
for example: 
![image](https://github.com/AzureAD/microsoft-identity-web/assets/30090357/143399bb-d05f-4d1b-8b9c-359148c70b6c)

2024-04-23 06:14 UTC, trwalke commented on build/template-onebranch-release-build.yaml
> +  BuildConfiguration: 'debug'
yes

2024-05-02 22:34 UTC, FuPingFranco approved these changes
LGTM, Thanks @trwalke!

2024-05-02 22:45 UTC, FuPingFranco commented
@trwalke Could you update the official release guidelines https://identitydivision.visualstudio.com/DevEx/_git/MISE?path=/docs/releases/OfficialReleases.md&version=GBmaster&_a=previewonce both PR's are in. Thanks!

2024-05-09 10:15 UTC, merged